//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriWise.RecursosLocalizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRecursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutriWise.RecursosLocalizables.StringRecursos", typeof(StringRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede repetir ningún plato..
        /// </summary>
        internal static string _0repetir {
            get {
                return ResourceManager.GetString("0repetir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad fisica.
        /// </summary>
        internal static string Actividad {
            get {
                return ResourceManager.GetString("Actividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dias a la semana.
        /// </summary>
        internal static string actividadcrear {
            get {
                return ResourceManager.GetString("actividadcrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad fisica x semana.
        /// </summary>
        internal static string ActividadFisica {
            get {
                return ResourceManager.GetString("ActividadFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agradecemos tus opiniones ♥.
        /// </summary>
        internal static string Agradecimiento {
            get {
                return ResourceManager.GetString("Agradecimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string agregar {
            get {
                return ResourceManager.GetString("agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Ingrediente Nuevo:.
        /// </summary>
        internal static string agregar1 {
            get {
                return ResourceManager.GetString("agregar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Ingrediente Nuevo:.
        /// </summary>
        internal static string agregar2 {
            get {
                return ResourceManager.GetString("agregar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Ingrediente Nuevo:.
        /// </summary>
        internal static string agregar3 {
            get {
                return ResourceManager.GetString("agregar3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Ingrediente Nuevo:.
        /// </summary>
        internal static string agregar4 {
            get {
                return ResourceManager.GetString("agregar4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La dieta ha sido agregada..
        /// </summary>
        internal static string agregardieta {
            get {
                return ResourceManager.GetString("agregardieta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Dieta:.
        /// </summary>
        internal static string agregardietita {
            get {
                return ResourceManager.GetString("agregardietita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AgregarIngredientes:.
        /// </summary>
        internal static string AgregarIng {
            get {
                return ResourceManager.GetString("AgregarIng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Platos:.
        /// </summary>
        internal static string agregarplatillo {
            get {
                return ResourceManager.GetString("agregarplatillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alergias/tolerancias.
        /// </summary>
        internal static string Alergias_tolerancias {
            get {
                return ResourceManager.GetString("Alergias/tolerancias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya hay un alimento con ese nombre en la base de datos..
        /// </summary>
        internal static string alimento1 {
            get {
                return ResourceManager.GetString("alimento1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AliPlato introducido en la base de datos correctamente..
        /// </summary>
        internal static string Aliplato {
            get {
                return ResourceManager.GetString("Aliplato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura.
        /// </summary>
        internal static string Altura {
            get {
                return ResourceManager.GetString("Altura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Apellidos).
        /// </summary>
        internal static string Apellido1 {
            get {
                return ResourceManager.GetString("Apellido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string Apellidos {
            get {
                return ResourceManager.GetString("Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string Ayuda {
            get {
                return ResourceManager.GetString("Ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string AyudaTitulo {
            get {
                return ResourceManager.GetString("AyudaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a NutriWise!.
        /// </summary>
        internal static string Bienvenida {
            get {
                return ResourceManager.GetString("Bienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        internal static string Bienvenida1 {
            get {
                return ResourceManager.GetString("Bienvenida1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrado de registro seleccionado. ¿Continuar?.
        /// </summary>
        internal static string borradito {
            get {
                return ResourceManager.GetString("borradito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string btnaceptarIngre {
            get {
                return ResourceManager.GetString("btnaceptarIngre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer.
        /// </summary>
        internal static string btnRestIngre {
            get {
                return ResourceManager.GetString("btnRestIngre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string btnVolverIngre {
            get {
                return ResourceManager.GetString("btnVolverIngre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string buscar {
            get {
                return ResourceManager.GetString("buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al buscar el usuario:.
        /// </summary>
        internal static string busqueda {
            get {
                return ResourceManager.GetString("busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar Cambios.
        /// </summary>
        internal static string cambiosaceptar {
            get {
                return ResourceManager.GetString("cambiosaceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad:.
        /// </summary>
        internal static string cant {
            get {
                return ResourceManager.GetString("cant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string cerrar_admin {
            get {
                return ResourceManager.GetString("cerrar_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clave incorrecta.
        /// </summary>
        internal static string Claveincorrecta {
            get {
                return ResourceManager.GetString("Claveincorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lactosa.
        /// </summary>
        internal static string cmbAdminPlatosInto {
            get {
                return ResourceManager.GetString("cmbAdminPlatosInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gluten.
        /// </summary>
        internal static string cmbAdminPlatosInto11 {
            get {
                return ResourceManager.GetString("cmbAdminPlatosInto11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vegano.
        /// </summary>
        internal static string cmbAdminPlatosInto21 {
            get {
                return ResourceManager.GetString("cmbAdminPlatosInto21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vegetariano.
        /// </summary>
        internal static string cmbAdminPlatosInto31 {
            get {
                return ResourceManager.GetString("cmbAdminPlatosInto31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin Intolerancia.
        /// </summary>
        internal static string cmbAdminPlatosInto41 {
            get {
                return ResourceManager.GetString("cmbAdminPlatosInto41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen.
        /// </summary>
        internal static string cmbAdminPlatosObj {
            get {
                return ResourceManager.GetString("cmbAdminPlatosObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definicion.
        /// </summary>
        internal static string cmbAdminPlatosObj11 {
            get {
                return ResourceManager.GetString("cmbAdminPlatosObj11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comer Sano.
        /// </summary>
        internal static string cmbAdminPlatosObj21 {
            get {
                return ResourceManager.GetString("cmbAdminPlatosObj21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desayuno.
        /// </summary>
        internal static string cmbAdminPlatosTipo {
            get {
                return ResourceManager.GetString("cmbAdminPlatosTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comida.
        /// </summary>
        internal static string cmbAdminPlatosTipo11 {
            get {
                return ResourceManager.GetString("cmbAdminPlatosTipo11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cena.
        /// </summary>
        internal static string cmbAdminPlatosTipo21 {
            get {
                return ResourceManager.GetString("cmbAdminPlatosTipo21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba.
        /// </summary>
        internal static string cmbIngre111 {
            get {
                return ResourceManager.GetString("cmbIngre111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba 1.
        /// </summary>
        internal static string cmbIngre121 {
            get {
                return ResourceManager.GetString("cmbIngre121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba 1.
        /// </summary>
        internal static string cmbIngre21 {
            get {
                return ResourceManager.GetString("cmbIngre21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba.
        /// </summary>
        internal static string cmbIngre211 {
            get {
                return ResourceManager.GetString("cmbIngre211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba.
        /// </summary>
        internal static string cmbIngre311 {
            get {
                return ResourceManager.GetString("cmbIngre311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba 1.
        /// </summary>
        internal static string cmbIngre312 {
            get {
                return ResourceManager.GetString("cmbIngre312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba.
        /// </summary>
        internal static string cmbIngre4 {
            get {
                return ResourceManager.GetString("cmbIngre4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba 1.
        /// </summary>
        internal static string cmbIngre41 {
            get {
                return ResourceManager.GetString("cmbIngre41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comer Sano.
        /// </summary>
        internal static string comersano {
            get {
                return ResourceManager.GetString("comersano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña.
        /// </summary>
        internal static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseñas no coinciden..
        /// </summary>
        internal static string Contraseñas_no_coinciden {
            get {
                return ResourceManager.GetString("Contraseñas no coinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato introducido en la base de datos correctamente..
        /// </summary>
        internal static string correctamente {
            get {
                return ResourceManager.GetString("correctamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un correo.
        /// </summary>
        internal static string correo_ingresa {
            get {
                return ResourceManager.GetString("correo_ingresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Correo).
        /// </summary>
        internal static string Correo1 {
            get {
                return ResourceManager.GetString("Correo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo incorrecto.
        /// </summary>
        internal static string Correoincorrecto {
            get {
                return ResourceManager.GetString("Correoincorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo introducido erróneo..
        /// </summary>
        internal static string Correointroducidoerróneo1 {
            get {
                return ResourceManager.GetString("Correointroducidoerróneo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo ya en uso, introduzca otro.
        /// </summary>
        internal static string Correoyaenusointroduzcaotro {
            get {
                return ResourceManager.GetString("Correoyaenusointroduzcaotro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        internal static string crear {
            get {
                return ResourceManager.GetString("crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porfavor introduzca sus credenciales.
        /// </summary>
        internal static string Credenciales {
            get {
                return ResourceManager.GetString("Credenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos incorrectos.
        /// </summary>
        internal static string datos_incorrectos {
            get {
                return ResourceManager.GetString("datos_incorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definición.
        /// </summary>
        internal static string definicion {
            get {
                return ResourceManager.GetString("definicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En volumen e intolerante a la lactosa.
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desea buscar el registro seleccionado. ¿Continuar?.
        /// </summary>
        internal static string desear {
            get {
                return ResourceManager.GetString("desear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dias.
        /// </summary>
        internal static string dias {
            get {
                return ResourceManager.GetString("dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dieta.
        /// </summary>
        internal static string Dieta {
            get {
                return ResourceManager.GetString("Dieta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string dieta_agregar {
            get {
                return ResourceManager.GetString("dieta_agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dieta agregada.
        /// </summary>
        internal static string dieta_añadida {
            get {
                return ResourceManager.GetString("dieta_añadida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dieta.
        /// </summary>
        internal static string DietaTitulo {
            get {
                return ResourceManager.GetString("DietaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dieta.
        /// </summary>
        internal static string dietita {
            get {
                return ResourceManager.GetString("dietita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Donación.
        /// </summary>
        internal static string donacion {
            get {
                return ResourceManager.GetString("donacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Donación.
        /// </summary>
        internal static string Donación {
            get {
                return ResourceManager.GetString("Donación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Donar.
        /// </summary>
        internal static string Donar {
            get {
                return ResourceManager.GetString("Donar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Donativos.
        /// </summary>
        internal static string Donativos {
            get {
                return ResourceManager.GetString("Donativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo introducido es erróneo.
        /// </summary>
        internal static string Elcorreointroducidoeserróneo {
            get {
                return ResourceManager.GetString("Elcorreointroducidoeserróneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo introducido no existe.
        /// </summary>
        internal static string Elcorreointroducidonoexiste {
            get {
                return ResourceManager.GetString("Elcorreointroducidonoexiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico:.
        /// </summary>
        internal static string elim_correo {
            get {
                return ResourceManager.GetString("elim_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca el correo electrónico del usuario
        ///que desea eliminar:.
        /// </summary>
        internal static string elim_info {
            get {
                return ResourceManager.GetString("elim_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminación de Usuarios:.
        /// </summary>
        internal static string elimi_usu {
            get {
                return ResourceManager.GetString("elimi_usu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminación.
        /// </summary>
        internal static string eliminacion {
            get {
                return ResourceManager.GetString("eliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se eliminó correctamente..
        /// </summary>
        internal static string eliminacion_correcta {
            get {
                return ResourceManager.GetString("eliminacion_correcta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string enviar {
            get {
                return ResourceManager.GetString("enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo introducido erróneo.
        /// </summary>
        internal static string erroneocito {
            get {
                return ResourceManager.GetString("erroneocito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: \nAliPlato introducido en la base de datos incorrectamente..
        /// </summary>
        internal static string error_aliplato {
            get {
                return ResourceManager.GetString("error_aliplato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido establecer conexión..
        /// </summary>
        internal static string error_conexion {
            get {
                return ResourceManager.GetString("error_conexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del plato incorrectos..
        /// </summary>
        internal static string error_platillo {
            get {
                return ResourceManager.GetString("error_platillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error conexión.
        /// </summary>
        internal static string error3 {
            get {
                return ResourceManager.GetString("error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar la valoración.
        /// </summary>
        internal static string Erroralenviarlavaloración {
            get {
                return ResourceManager.GetString("Erroralenviarlavaloración", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con la base de datos..
        /// </summary>
        internal static string errordatos {
            get {
                return ResourceManager.GetString("errordatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró ningún usuario con el correo especificado..
        /// </summary>
        internal static string falta_especificar {
            get {
                return ResourceManager.GetString("falta_especificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string fecha_admin {
            get {
                return ResourceManager.GetString("fecha_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gluten.
        /// </summary>
        internal static string gluten {
            get {
                return ResourceManager.GetString("gluten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido Usuario (USER).
        /// </summary>
        internal static string info_admin {
            get {
                return ResourceManager.GetString("info_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        internal static string informacion {
            get {
                return ResourceManager.GetString("informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Ingredientes.
        /// </summary>
        internal static string ingre {
            get {
                return ResourceManager.GetString("ingre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrediente 1.
        /// </summary>
        internal static string ingre1 {
            get {
                return ResourceManager.GetString("ingre1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrediente 2.
        /// </summary>
        internal static string ingre2 {
            get {
                return ResourceManager.GetString("ingre2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrediente 3.
        /// </summary>
        internal static string ingre3 {
            get {
                return ResourceManager.GetString("ingre3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrediente 4.
        /// </summary>
        internal static string ingre4 {
            get {
                return ResourceManager.GetString("ingre4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrediente.
        /// </summary>
        internal static string ingrediente {
            get {
                return ResourceManager.GetString("ingrediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe selccionar 4 ingredientes por plato..
        /// </summary>
        internal static string ingredientes4 {
            get {
                return ResourceManager.GetString("ingredientes4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un correo..
        /// </summary>
        internal static string Ingrese_un_correo {
            get {
                return ResourceManager.GetString("Ingrese un correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión correcto.
        /// </summary>
        internal static string Iniciodesesióncorrecto {
            get {
                return ResourceManager.GetString("Iniciodesesióncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Platos insuficientes.
        /// </summary>
        internal static string insuficiente {
            get {
                return ResourceManager.GetString("insuficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intolerancias:.
        /// </summary>
        internal static string into {
            get {
                return ResourceManager.GetString("into", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Laclaveintroducidaesincorrecta.
        /// </summary>
        internal static string Laclaveintroducidaesincorrecta {
            get {
                return ResourceManager.GetString("Laclaveintroducidaesincorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lactosa.
        /// </summary>
        internal static string lactosa {
            get {
                return ResourceManager.GetString("lactosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las valoraciones son anonimas.
        /// </summary>
        internal static string Lasvaloracionessonanonimas {
            get {
                return ResourceManager.GetString("Lasvaloracionessonanonimas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrediente 1.
        /// </summary>
        internal static string lblIng1 {
            get {
                return ResourceManager.GetString("lblIng1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrediente 2.
        /// </summary>
        internal static string lblIng2 {
            get {
                return ResourceManager.GetString("lblIng2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrediente 3.
        /// </summary>
        internal static string lblIng3 {
            get {
                return ResourceManager.GetString("lblIng3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrediente 4.
        /// </summary>
        internal static string lblIng4 {
            get {
                return ResourceManager.GetString("lblIng4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de la compra.
        /// </summary>
        internal static string ListaCompra {
            get {
                return ResourceManager.GetString("ListaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista.
        /// </summary>
        internal static string ListaTitulo {
            get {
                return ResourceManager.GetString("ListaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mantenimiento.
        /// </summary>
        internal static string mantenimiento {
            get {
                return ResourceManager.GetString("mantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error:\nLos platos deben tener 4 ingredientes.\nLos platos una cantidad mayor que 0..
        /// </summary>
        internal static string mayorque0 {
            get {
                return ResourceManager.GetString("mayorque0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jaja Pringao.
        /// </summary>
        internal static string mensaje {
            get {
                return ResourceManager.GetString("mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jaja Pringao.
        /// </summary>
        internal static string MensajePringao {
            get {
                return ResourceManager.GetString("MensajePringao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si tiene algún problema contacte  con el siguiente correo: nutriwiseinformacion@gmail.com O llame al número: 696942069.
        /// </summary>
        internal static string MenuAyuda {
            get {
                return ResourceManager.GetString("MenuAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes ingresar como mínimo 1 plato..
        /// </summary>
        internal static string minimo1 {
            get {
                return ResourceManager.GetString("minimo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ninguna.
        /// </summary>
        internal static string ninguna {
            get {
                return ResourceManager.GetString("ninguna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ningún plato seleccionado.
        /// </summary>
        internal static string ningunoselec {
            get {
                return ResourceManager.GetString("ningunoselec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró ningún usuario con el correo especificado..
        /// </summary>
        internal static string no_encontradito {
            get {
                return ResourceManager.GetString("no_encontradito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe conexión a la Base de Datos.
        /// </summary>
        internal static string no_existir {
            get {
                return ResourceManager.GetString("no_existir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay platos suficientes para crear una dieta..
        /// </summary>
        internal static string no_platos {
            get {
                return ResourceManager.GetString("no_platos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        internal static string nocuenta {
            get {
                return ResourceManager.GetString("nocuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes ingresar un nombre y seleccionar un tipo de objetivo y de intolerancia..
        /// </summary>
        internal static string nombre_objetivo {
            get {
                return ResourceManager.GetString("nombre_objetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Nombre).
        /// </summary>
        internal static string Nombre1 {
            get {
                return ResourceManager.GetString("Nombre1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de la Dieta:.
        /// </summary>
        internal static string nombredietilla {
            get {
                return ResourceManager.GetString("nombredietilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Plato:.
        /// </summary>
        internal static string nombreplatillo {
            get {
                return ResourceManager.GetString("nombreplatillo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivo:.
        /// </summary>
        internal static string obj {
            get {
                return ResourceManager.GetString("obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivo.
        /// </summary>
        internal static string Objetivo {
            get {
                return ResourceManager.GetString("Objetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He olvidado mi contraseña.
        /// </summary>
        internal static string olvidar {
            get {
                return ResourceManager.GetString("olvidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operaciones.
        /// </summary>
        internal static string operar {
            get {
                return ResourceManager.GetString("operar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a para gente en definición.
        /// </summary>
        internal static string para1 {
            get {
                return ResourceManager.GetString("para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a para celiacos.
        /// </summary>
        internal static string para2 {
            get {
                return ResourceManager.GetString("para2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string PerfilTitulo {
            get {
                return ResourceManager.GetString("PerfilTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso.
        /// </summary>
        internal static string Peso {
            get {
                return ResourceManager.GetString("Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato.
        /// </summary>
        internal static string plato {
            get {
                return ResourceManager.GetString("plato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string plato_agregar {
            get {
                return ResourceManager.GetString("plato_agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: \nYa hay un plato con ese nombre en la base de datos..
        /// </summary>
        internal static string plato_existente {
            get {
                return ResourceManager.GetString("plato_existente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: \nPlato introducido en la base de datos incorrectamente..
        /// </summary>
        internal static string plato_incorrecto {
            get {
                return ResourceManager.GetString("plato_incorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 1:.
        /// </summary>
        internal static string plato1 {
            get {
                return ResourceManager.GetString("plato1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 10:.
        /// </summary>
        internal static string plato10 {
            get {
                return ResourceManager.GetString("plato10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 11:.
        /// </summary>
        internal static string plato11 {
            get {
                return ResourceManager.GetString("plato11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 12:.
        /// </summary>
        internal static string plato12 {
            get {
                return ResourceManager.GetString("plato12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 13:.
        /// </summary>
        internal static string plato13 {
            get {
                return ResourceManager.GetString("plato13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 14:.
        /// </summary>
        internal static string plato14 {
            get {
                return ResourceManager.GetString("plato14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 15:.
        /// </summary>
        internal static string plato15 {
            get {
                return ResourceManager.GetString("plato15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 16:.
        /// </summary>
        internal static string plato16 {
            get {
                return ResourceManager.GetString("plato16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 17:.
        /// </summary>
        internal static string plato17 {
            get {
                return ResourceManager.GetString("plato17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 18:.
        /// </summary>
        internal static string plato18 {
            get {
                return ResourceManager.GetString("plato18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 19:.
        /// </summary>
        internal static string plato19 {
            get {
                return ResourceManager.GetString("plato19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 2:.
        /// </summary>
        internal static string plato2 {
            get {
                return ResourceManager.GetString("plato2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 20:.
        /// </summary>
        internal static string plato20 {
            get {
                return ResourceManager.GetString("plato20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 21:.
        /// </summary>
        internal static string plato21 {
            get {
                return ResourceManager.GetString("plato21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 3:.
        /// </summary>
        internal static string plato3 {
            get {
                return ResourceManager.GetString("plato3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 4:.
        /// </summary>
        internal static string plato4 {
            get {
                return ResourceManager.GetString("plato4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 5:.
        /// </summary>
        internal static string plato5 {
            get {
                return ResourceManager.GetString("plato5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 6:.
        /// </summary>
        internal static string plato6 {
            get {
                return ResourceManager.GetString("plato6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 7:.
        /// </summary>
        internal static string plato7 {
            get {
                return ResourceManager.GetString("plato7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 8:.
        /// </summary>
        internal static string plato8 {
            get {
                return ResourceManager.GetString("plato8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plato 9:.
        /// </summary>
        internal static string plato9 {
            get {
                return ResourceManager.GetString("plato9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string PlatoAceptar {
            get {
                return ResourceManager.GetString("PlatoAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer.
        /// </summary>
        internal static string PlatoReset {
            get {
                return ResourceManager.GetString("PlatoReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay platos suficientes para crear una dieta..
        /// </summary>
        internal static string platos_insu {
            get {
                return ResourceManager.GetString("platos_insu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Platos insuficientes.
        /// </summary>
        internal static string platos_insu2 {
            get {
                return ResourceManager.GetString("platos_insu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string PlatoVolver {
            get {
                return ResourceManager.GetString("PlatoVolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Receta.
        /// </summary>
        internal static string Receta {
            get {
                return ResourceManager.GetString("Receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hora.
        /// </summary>
        internal static string reloj_admin {
            get {
                return ResourceManager.GetString("reloj_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede repetirse ningun alimento..
        /// </summary>
        internal static string repetiralimento {
            get {
                return ResourceManager.GetString("repetiralimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Platos repetidos.
        /// </summary>
        internal static string repetirplato {
            get {
                return ResourceManager.GetString("repetirplato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string salir_admin {
            get {
                return ResourceManager.GetString("salir_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dias a la semana.
        /// </summary>
        internal static string Semana {
            get {
                return ResourceManager.GetString("Semana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión.
        /// </summary>
        internal static string sesion1 {
            get {
                return ResourceManager.GetString("sesion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesion.
        /// </summary>
        internal static string sesion2 {
            get {
                return ResourceManager.GetString("sesion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin Intolerancias.
        /// </summary>
        internal static string sinintolerancias {
            get {
                return ResourceManager.GetString("sinintolerancias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen.
        /// </summary>
        internal static string TipoObjetivo {
            get {
                return ResourceManager.GetString("TipoObjetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lactosa.
        /// </summary>
        internal static string Tolerancias {
            get {
                return ResourceManager.GetString("Tolerancias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tolerancias.
        /// </summary>
        internal static string Tolerancias1 {
            get {
                return ResourceManager.GetString("Tolerancias1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string usuario_eliminar {
            get {
                return ResourceManager.GetString("usuario_eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el usuario:.
        /// </summary>
        internal static string usuario_eliminar1 {
            get {
                return ResourceManager.GetString("usuario_eliminar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario inexistente.
        /// </summary>
        internal static string Usuarioinexistente {
            get {
                return ResourceManager.GetString("Usuarioinexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración enviada.
        /// </summary>
        internal static string Valoraciónenviada {
            get {
                return ResourceManager.GetString("Valoraciónenviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoración enviada con éxito.
        /// </summary>
        internal static string Valoraciónenviadaconéxito {
            get {
                return ResourceManager.GetString("Valoraciónenviadaconéxito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoraciones.
        /// </summary>
        internal static string Valoraciones {
            get {
                return ResourceManager.GetString("Valoraciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoraciones.
        /// </summary>
        internal static string ValoracionesTitulo {
            get {
                return ResourceManager.GetString("ValoracionesTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Valor Nutricional:.
        /// </summary>
        internal static string valorN1 {
            get {
                return ResourceManager.GetString("valorN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Valor Nutricional:.
        /// </summary>
        internal static string valorN2 {
            get {
                return ResourceManager.GetString("valorN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Valor Nutricional:.
        /// </summary>
        internal static string valorN3 {
            get {
                return ResourceManager.GetString("valorN3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir Valor Nutricional:.
        /// </summary>
        internal static string valorN4 {
            get {
                return ResourceManager.GetString("valorN4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vegano.
        /// </summary>
        internal static string vegano {
            get {
                return ResourceManager.GetString("vegano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vegetariano.
        /// </summary>
        internal static string vegetariano {
            get {
                return ResourceManager.GetString("vegetariano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Videos.
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Videos.
        /// </summary>
        internal static string VideosTitulo {
            get {
                return ResourceManager.GetString("VideosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen.
        /// </summary>
        internal static string volumen {
            get {
                return ResourceManager.GetString("volumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string volver_elim {
            get {
                return ResourceManager.GetString("volver_elim", resourceCulture);
            }
        }
    }
}
