//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriWise.RecursosLocalizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRecursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutriWise.RecursosLocalizables.StringRecursos", typeof(StringRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad fisica.
        /// </summary>
        internal static string Actividad {
            get {
                return ResourceManager.GetString("Actividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad fisica x semana.
        /// </summary>
        internal static string ActividadFisica {
            get {
                return ResourceManager.GetString("ActividadFisica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alergias/tolerancias.
        /// </summary>
        internal static string Alergias_tolerancias {
            get {
                return ResourceManager.GetString("Alergias/tolerancias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura.
        /// </summary>
        internal static string Altura {
            get {
                return ResourceManager.GetString("Altura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string Apellidos {
            get {
                return ResourceManager.GetString("Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ayuda.
        /// </summary>
        internal static string Ayuda {
            get {
                return ResourceManager.GetString("Ayuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a NutriWise!.
        /// </summary>
        internal static string Bienvenida {
            get {
                return ResourceManager.GetString("Bienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        internal static string Bienvenida1 {
            get {
                return ResourceManager.GetString("Bienvenida1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        internal static string Confirmar {
            get {
                return ResourceManager.GetString("Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        internal static string crear {
            get {
                return ResourceManager.GetString("crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porfavor introduzca sus credenciales.
        /// </summary>
        internal static string Credenciales {
            get {
                return ResourceManager.GetString("Credenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En volumen e intolerante a la lactosa.
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3 dias .
        /// </summary>
        internal static string dias {
            get {
                return ResourceManager.GetString("dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dieta.
        /// </summary>
        internal static string Dieta {
            get {
                return ResourceManager.GetString("Dieta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Donación.
        /// </summary>
        internal static string Donación {
            get {
                return ResourceManager.GetString("Donación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Donar.
        /// </summary>
        internal static string Donar {
            get {
                return ResourceManager.GetString("Donar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Donativos.
        /// </summary>
        internal static string Donativos {
            get {
                return ResourceManager.GetString("Donativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intolerancias.
        /// </summary>
        internal static string Intolerancias {
            get {
                return ResourceManager.GetString("Intolerancias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de la compra.
        /// </summary>
        internal static string ListaCompra {
            get {
                return ResourceManager.GetString("ListaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si tiene algún problema contacte 
        ///con el siguiente correo:
        ///nutriwiseinformacion@gmail.com
        ///
        ///O llame al número:
        ///696942069.
        /// </summary>
        internal static string MenuAyuda {
            get {
                return ResourceManager.GetString("MenuAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        internal static string nocuenta {
            get {
                return ResourceManager.GetString("nocuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivo.
        /// </summary>
        internal static string Objetivo {
            get {
                return ResourceManager.GetString("Objetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He olvidado mi contraseña.
        /// </summary>
        internal static string olvidar {
            get {
                return ResourceManager.GetString("olvidar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a para gente en definición.
        /// </summary>
        internal static string para1 {
            get {
                return ResourceManager.GetString("para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a para celiacos.
        /// </summary>
        internal static string para2 {
            get {
                return ResourceManager.GetString("para2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso.
        /// </summary>
        internal static string Peso {
            get {
                return ResourceManager.GetString("Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Receta.
        /// </summary>
        internal static string Receta {
            get {
                return ResourceManager.GetString("Receta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dias a la semana.
        /// </summary>
        internal static string Semana {
            get {
                return ResourceManager.GetString("Semana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesion.
        /// </summary>
        internal static string sesion {
            get {
                return ResourceManager.GetString("sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión.
        /// </summary>
        internal static string sesion1 {
            get {
                return ResourceManager.GetString("sesion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen.
        /// </summary>
        internal static string TipoObjetivo {
            get {
                return ResourceManager.GetString("TipoObjetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lactosa.
        /// </summary>
        internal static string Tolerancias {
            get {
                return ResourceManager.GetString("Tolerancias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoraciones.
        /// </summary>
        internal static string Valoraciones {
            get {
                return ResourceManager.GetString("Valoraciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Videos.
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
    }
}
